### ISSUE TITLE
Bean validation - anonymous complex types

### ISSUE THREAD

**Issue by zsenyeg** [phax/ph-jaxb22-plugin#2]
Hey Philip,

it's meg again with another little problem. Can you test your plugin with the attached xsd pls? 
It's seems to me @Valid annotation is not added properly when schema contains anonymous complex type definitions.

@Valid annotation is missing from generated top level member:

```
@NotNull
protected TestType.Stringlist stringlist;
```
Test schema file (could not attach with xsd extension)
[test.txt](https://github.com/phax/ph-jaxb22-plugin/files/3685909/test.txt)

Best regards,

Zsolt

**Comment by phax** [comment]
Thanks for pointing this out. Fixed and will create a new release

**Comment by zsenyeg** [comment]
Hey,

thanks for the fix,

Cheers
Zsolt
